version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "b"
    directory: "u"
    schedule:
      interval: "weekly"

  - package-ecosystem: "/"
    directory: ""
    schedule:
      interval: "weekly"
